name: herokuCI
on:
  push:
    branches:
      - master
jobs:
  app1:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker to Heroku
        env:
          HEROKU_APP_NAME: <app_name>
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          DOCKERFILE_NAME: "Dockerfile.web"
        run: |
          echo ${HEROKU_API_KEY} | docker login --username=${HEROKU_EMAIL} registry.heroku.com --password-stdin
          docker build --file ${DOCKERFILE_NAME} --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
          heroku container:push --recursive --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}
