name: firebaseCI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # add the backend url with envsubst 
      - uses: danielr1996/envsubst-action@1.0.0
        env:
            API_URL: http://TEST:8080/api
        with:
          input: src/assets/env.template.js
          output: src/assets/env.js

      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: archived_deploy_dist
          path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: archived_deploy_dist

      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: archived_deploy_dist/angular-ci-test

